name: Pint

on:
  push:
    paths:
      - "**.php"

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          preset: laravel
          verboseMode: true
          testMode: true
