name: Pint

on:
  push:
    paths:
      - "**.php"

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      name: Pint
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: "ubuntu-latest"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test -v
