name: Static analysis

on:
  push:
    paths:
      - "**.php"
      - "phpstan.neon.dist"
      - ".github/workflows/static-analysis.yml"

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        stability: [prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
